### ISSUE TITLE
pyGTrends isn't installable via pip

### ISSUE THREAD

**Issue by hyperair** [suryasev/unofficial-google-trends-api#6]
% pip install pyGTrends
Downloading/unpacking pyGTrends
  Could not find any downloads that satisfy the requirement pyGTrends
No distributions at all found for pyGTrends
Storing complete log in /home/hyperair/.pip/pip.log

**Comment by hyperair** [comment]
## Here's the install log.

/home/hyperair/.virtualenvs/healthmeter/bin/pip run on Wed Dec  5 15:12:18 2012
Downloading/unpacking pyGTrends

  Getting page http://pypi.python.org/simple/pyGTrends
  URLs to search for versions for pyGTrends:
- http://pypi.python.org/simple/pyGTrends/
  Getting page http://www.juiceanalytics.com/openjuice/programmatic-google-trends-api/
  Getting page http://media.juiceanalytics.com/downloads/pyGTrends.py
  Getting page http://github.com/suryasev/unofficial-google-trends-api/archives/master
  Analyzing links from page http://pypi.python.org/simple/pyGTrends/
    Skipping link http://www.juiceanalytics.com/openjuice/programmatic-google-trends-api/ (from http://pypi.python.org/simple/pyGTrends/); not a file
    Skipping link http://media.juiceanalytics.com/downloads/pyGTrends.py (from http://pypi.python.org/simple/pyGTrends/); unknown archive format: .py
    Skipping link http://github.com/suryasev/unofficial-google-trends-api/archives/master (from http://pypi.python.org/simple/pyGTrends/); not a file
  Analyzing links from page http://www.juiceanalytics.com/writing/programmatic-google-trends-api/
    Skipping link http://www.juiceanalytics.com/wp-content/themes/juiceanalytics3/_ui/css/main.css (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .css
    Skipping link http://www.juiceanalytics.com/wp-content/themes/juiceanalytics3/_ui/css/ie.css (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .css
    Skipping link http://www.juiceanalytics.com/wp-content/themes/juiceanalytics3/_ui/css/print.css (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .css
    Skipping link http://www.juiceanalytics.com/wp-content/themes/juiceanalytics3/_ui/css/lightwindow.css (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .css
    Skipping link http://www.juiceanalytics.com/xmlrpc.php (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .php
    Skipping link http://www.juiceanalytics.com/wp-content/themes/juiceanalytics3/_ui/images/favicon.ico (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .ico
    Skipping link http://www.juiceanalytics.com/feed/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/comments/feed/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/programmatic-google-trends-api/feed/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/wp-content/plugins/contact-form-7/styles.css?ver=3.1.1 (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .css
    Skipping link http://www.juiceanalytics.com/wp-content/plugins/wp-pagenavi/pagenavi-css.css?ver=2.70 (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .css
    Skipping link http://www.juiceanalytics.com/xmlrpc.php?rsd (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .php
    Skipping link http://www.juiceanalytics.com/wp-includes/wlwmanifest.xml (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .xml
    Skipping link http://www.juiceanalytics.com/writing/clever-not-equal-smart-naming/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/microsofts-executive-dashboard/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/programmatic-google-trends-api/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/?p=419 (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/programmatic-google-trends-api/#navigation (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/programmatic-google-trends-api/#content (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/programmatic-google-trends-api/#sidebar (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/login/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/slice/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/dashboard-and-application-design/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/case-studies/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/gallery/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/chart-chooser/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/gallery/leaderboard-of-2012-nfl-combine-players/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://analyticsvisualizations.appspot.com/juicekit/AnalyticsVisualization.html (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .html
    Skipping link http://www.juiceanalytics.com/writing/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/visitors-guide/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/visualization-resources/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/white-papers-guides-and-more/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://labs.juiceanalytics.com/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/design-principles/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/free-tools/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/about-juice/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/perspective/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/jobs-at-juice/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/contact-us/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/blog/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/author/Sal-Uryasev/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://googleblog.blogspot.com/2008/06/new-flavor-of-google-trends.html (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .html
    Skipping link http://github.com/suryasev/unofficial-google-trends-api/tree/master (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://google.com/trends (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/tags/api/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/tags/google/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/tags/programmatic/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/tags/trends/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://twitter.com/share (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.ibiblio.org/g2swap/byteofpython/read/self.html (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .html
    Skipping link http://www.thirtydaychallenge.com/forums/general-chat/5364-google-trends-limit-wtf.html (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .html
    Skipping link mailto:sivatumma@hotmail.com (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .com
    Skipping link http://banfieldfleafighter.com (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link https://github.com/jdmunro/unofficial-google-trends-api (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://feeds.feedburner.com/JuiceAnalytics (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/nfl-rushing-tendency-visualization/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/big-data-intimate-stories-big-impact/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/are-you-ready-for-some-football-we-are/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/designing-a-better-sales-pipeline-dashboard/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/have-juice-with-juice-at-product-camp-atlanta-2012/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/choosing-right-metric/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/last-mile-business-intelligence/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/why-analytical-applications-fail/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/5-phases-data-analytics-maturation-part-1/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/colbert-bump/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/excel-geocoding-tool-v2/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/writing/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/book-reviews/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/business-intelligence/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/dashboard-design/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/analysis/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/data-structure/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/demo/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/events/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/information-presentation/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/information-visualization/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/news/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/people/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/redesigns/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/small-talk/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/step-by-step/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/tools-tips/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/visualization-challenges/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.juiceanalytics.com/writing/category/visualization-tools/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://www.twitter.com/juiceanalytics (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=11529+Sunrise+Valley+Drive,+%238+Reston,+VA+20191+&amp;sll=33.914054,-84.341411&amp;sspn=0.015848,0.02208&amp;ie=UTF8&amp;hq=&amp;hnear=11529+Sunrise+Valley+Dr,+Reston,+Fairfax,+Virginia+20191&amp;ll=38.919353,-77.235947&amp;spn=0.475466,0.706558&amp;z=11&amp;iwloc=A (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=115+Perimeter+Center+Place,+Suite+570+30346&aq=&sll=37.0625,-95.677068&sspn=42.85226,89.472656&ie=UTF8&hq=&hnear=115+Perimeter+Center+Pl+%23570,+Dunwoody,+DeKalb,+Georgia+30346&ll=33.920572,-84.337921&spn=0.352128,0.699005&z=11 (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
    Skipping link mailto:info@juiceanalytics.com (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .com
    Skipping link http://www.juiceanalytics.com/wp-content/themes/juiceanalytics3/_media/Juice%20Analytics.vcf (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); unknown archive format: .vcf
    Skipping link http://www.juiceanalytics.com/privacy/ (from http://www.juiceanalytics.com/writing/programmatic-google-trends-api/); not a file
  Analyzing links from page http://media.juiceanalytics.com/downloads/pyGTrends.py
  Analyzing links from page https://github.com/suryasev/unofficial-google-trends-api/downloads
    Skipping link https://github.com/opensearch.xml (from https://github.com/suryasev/unofficial-google-trends-api/downloads); unknown archive format: .xml
    Skipping link https://github.com/fluidicon.png (from https://github.com/suryasev/unofficial-google-trends-api/downloads); unknown archive format: .png
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/apple-touch-icon-114.png (from https://github.com/suryasev/unofficial-google-trends-api/downloads); unknown archive format: .png
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/apple-touch-icon-144.png (from https://github.com/suryasev/unofficial-google-trends-api/downloads); unknown archive format: .png
    Skipping link https://github.com/favicon.ico (from https://github.com/suryasev/unofficial-google-trends-api/downloads); unknown archive format: .ico
    Skipping link https://a248.e.akamai.net/assets.github.com/assets/github-bd7a9aac1964f57509ff6d9dbddc6e086343bca4.css (from https://github.com/suryasev/unofficial-google-trends-api/downloads); unknown archive format: .css
    Skipping link https://a248.e.akamai.net/assets.github.com/assets/github2-7ac48c6a5682be9186910ce0e13140ebadea3d88.css (from https://github.com/suryasev/unofficial-google-trends-api/downloads); unknown archive format: .css
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/commits/master.atom (from https://github.com/suryasev/unofficial-google-trends-api/downloads); unknown archive format: .atom
    Skipping link https://github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/explore (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/search (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/features (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/blog (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/signup (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/login?return_to=%2Fsuryasev%2Funofficial-google-trends-api%2Fdownloads (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/login?return_to=%2Fsuryasev%2Funofficial-google-trends-api (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/stargazers (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/network (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/suryasev (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/suryasev/unofficial-google-trends-api (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/pulls (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/issues (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/graphs (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/tags (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/downloads (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/commits/master (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/branches (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Could not parse version from link: https://github.com/suryasev/unofficial-google-trends-api/archive/master.zip (from https://github.com/suryasev/unofficial-google-trends-api/downloads)
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/archive/master.zip (from https://github.com/suryasev/unofficial-google-trends-api/downloads); wrong project name (not pygtrends)
    Could not parse version from link: https://github.com/suryasev/unofficial-google-trends-api/archive/master.tar.gz (from https://github.com/suryasev/unofficial-google-trends-api/downloads)
    Skipping link https://github.com/suryasev/unofficial-google-trends-api/archive/master.tar.gz (from https://github.com/suryasev/unofficial-google-trends-api/downloads); wrong project name (not pygtrends)
    Skipping link https://github.com/about (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/contact (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://enterprise.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://status.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://mac.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://windows.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://eclipse.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://mobile.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://get.gaug.es/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://speakerdeck.com (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://gist.github.com (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://jobs.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://help.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://developer.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://github.github.com/github-flavored-markdown/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://pages.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://training.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/edu (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://shop.github.com (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link http://octodex.github.com/ (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/site/terms (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/site/privacy (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
    Skipping link https://github.com/security (from https://github.com/suryasev/unofficial-google-trends-api/downloads); not a file
  Could not find any downloads that satisfy the requirement pyGTrends

No distributions at all found for pyGTrends

Exception information:
Traceback (most recent call last):
  File "/home/hyperair/.virtualenvs/healthmeter/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/home/hyperair/.virtualenvs/healthmeter/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/hyperair/.virtualenvs/healthmeter/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 978, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/hyperair/.virtualenvs/healthmeter/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/index.py", line 157, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for pyGTrends
